"use client";

import { motion } from "framer-motion";
import { Check, X, Clock, Sparkles } from "lucide-react";
import { Topbar } from "@/components/layout/topbar";
import { PageTransition } from "@/components/layout/page-transition";
import { GlassCard } from "@/components/ui/glass-card";
import { StatusChip } from "@/components/ui/status-chip";
import { Button } from "@/components/ui/button";
import { mockMessages } from "@/lib/mock-data";
import { relativeTime } from "@/lib/utils";

export default function OutreachPage() {
  return (
    <PageTransition>
      <Topbar title="Outreach" subtitle="Review, approve, and schedule AI-drafted messages" />

      <div className="px-6 py-6 space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {[
            { label: "Pending approval", count: 12, color: "bg-accent" },
            { label: "Scheduled", count: 47, color: "bg-blue-500" },
            { label: "Sent today", count: 134, color: "bg-emerald-500" },
          ].map((s, i) => (
            <motion.div key={s.label} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.05 }}>
              <GlassCard padding="md" hoverable>
                <div className="flex items-center gap-3">
                  <span className={`w-2 h-2 rounded-full ${s.color} animate-pulse-soft`} />
                  <span className="text-xs uppercase tracking-wider text-ink-500">{s.label}</span>
                </div>
                <div className="text-3xl font-bold text-ink-900 mt-3 tabular-nums">{s.count}</div>
              </GlassCard>
            </motion.div>
          ))}
        </div>

        <GlassCard padding="md">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold text-ink-900">Approval queue</h3>
            <div className="text-xs text-ink-500">Drafts generated by AI</div>
          </div>

          <div className="space-y-3">
            {mockMessages.map((m, i) => (
              <motion.div
                key={m.id}
                initial={{ opacity: 0, x: -8 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.06 }}
                whileHover={{ scale: 1.005 }}
                className="bg-white/50 border border-white/60 rounded-xl p-4 hover:bg-white/70 transition-colors"
              >
                <div className="flex items-start justify-between gap-3 mb-2">
                  <div className="flex items-center gap-2">
                    <Sparkles className="w-3.5 h-3.5 text-accent" />
                    <span className="font-medium text-ink-900 text-sm">{m.leadName}</span>
                    <span className="text-xs text-ink-400">·</span>
                    <span className="text-xs text-ink-500">{m.kind.replace("_", " ").toLowerCase()}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <StatusChip status={m.status} />
                    <span className="text-xs text-ink-400 flex items-center gap-1"><Clock className="w-3 h-3" />{relativeTime(m.createdAt)}</span>
                  </div>
                </div>
                <p className="text-sm text-ink-700 leading-relaxed mb-3">{m.body}</p>
                {m.status === "PENDING_APPROVAL" && (
                  <div className="flex gap-2">
                    <Button size="sm" variant="primary"><Check className="w-3.5 h-3.5" /> Approve</Button>
                    <Button size="sm" variant="ghost">Edit</Button>
                    <Button size="sm" variant="ghost"><X className="w-3.5 h-3.5" /> Reject</Button>
                  </div>
                )}
              </motion.div>
            ))}
          </div>
        </GlassCard>
      </div>
    </PageTransition>
  );
}
